services:
  postgresdb:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: myappdb
      # Pulls from .env file
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-postgres-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d myappdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring_app_container
    ports:
      - "8080:8080"
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/myappdb
      # Pass the .env variables into the Spring container
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - spring-postgres-net

networks:
  spring-postgres-net:
    driver: bridge

volumes:
  postgres_data: